[workspace]
resolver = "2"
members = ["core", "cli"]

[workspace.package]
edition = "2024"
license = "MIT"
authors = ["Reinhard Bronner"]

[workspace.dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
ureq = "2"
md-5 = "0.10"
sha2 = "0.10"
getrandom = "0.2"
rpassword = "7"
