[package]
name = "sparrow-cannon-core"
version = "0.0.1"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
toml.workspace = true
ureq.workspace = true
md-5.workspace = true
sha2.workspace = true
getrandom.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
russh = "0.45"
russh-keys = "0.45"
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "time"] }
async-trait = "0.1"
libc = "0.2"
tracing.workspace = true
