[package]
name = "sparrow-cannon-core"
version = "0.0.1"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
toml.workspace = true
ureq.workspace = true
md-5.workspace = true
sha2.workspace = true
getrandom.workspace = true
